### ISSUE TITLE
Could you add Vietnamese as a target language?

### ISSUE THREAD

**Issue by bun906** [sh2/extension-summarize-translate-gemini#2]
Could you add Vietnamese as a target language? Great app, but I can't translate other languages into Vietnamese.
Thanks.

**Comment by sh2** [comment]
Gemini supports Vietnamese, so you can use custom actions to handle it. Open the Options page and set the following custom actions.

When no text is selected, do the following action:
```
Summarize the entire text as Markdown numbered list in Vietnamese and reply only with the list.
Format:
1. First point.
2. Second point.
3. Third point.
```

When text is selected, do the following action:
```
Translate the entire text into Vietnamese and reply only with the translated result.
```

![image](https://github.com/sh2/extension-summarize-translate-gemini/assets/1710774/10b000c0-633f-4505-beb9-c48948f9457b)

Adding support for more languages would increase the burden of development and testing, so we will be adding support gradually. Until then, please use custom actions.

Best regards,

**Comment by bun906** [comment]
It helps a lot, thank you.

**Comment by bun906** [comment]
Yessss Thank you very much.
