### ISSUE TITLE
Summarize-translate-gemini for Firefox

### ISSUE THREAD

**Issue by Dan9026** [sh2/extension-summarize-translate-gemini#3]
Can you create an extension for Firefox? I really like this extension, but unfortunately it's only available for Chrome.

**Comment by sh2** [comment]
With a slight change in the code, it appears to work in both Chrome and Firefox.
I will work on Firefox support, but it will take a while.

**Comment by Dan9026** [comment]
Thanks. You're the best.

**Comment by sh2** [comment]
Firefox is now supported and registered in [Firefox add-ons](https://addons.mozilla.org/firefox/addon/summarize-translate-gemini/).
Feel free to try it out!

**Comment by Dan9026** [comment]
Thanksssssssss
