### ISSUE TITLE
Option for followup questions

### ISSUE THREAD

**Issue by mderazon** [sh2/extension-summarize-translate-gemini#4]
First off, this extension is REALLY good thank you for that!

I think it would be cool if we could provide it with a follow up prompt, after the summary to ask additional questions about the summarized article.

**Comment by sh2** [comment]
Thank you very much for using this tool!

I too would like the ability to ask follow-up questions, so I will look into how to implement.
It will take some time, so please be patient.

**Comment by sh2** [comment]
In version 1.5.0, this tool now has the ability to ask follow-up questions from the results page.
Try it out :-)

![results_e](https://github.com/user-attachments/assets/0d6cdb35-01d9-41e6-9f13-1c1ee2a962d9)

Commit: a27921e0e95545386184b04d521fd6aac2ccd310

**Comment by mderazon** [comment]
This looks awesome, thank you !

**Comment by mderazon** [comment]
@sh2 is this released on the web stores yet ? As I can't seem to find the option until now

**Comment by sh2** [comment]
Released to Chrome Web Store, etc.
To ask a follow-up question, press “Open results in a new tab” from the pop-up.

**Comment by mderazon** [comment]
> Released to Chrome Web Store, etc. To ask a follow-up question, press “Open results in a new tab” from the pop-up.

That did the trick. Thanks
